[package]
name = "feed-browser"
version = "0.1.0"
authors = ["Patrick Gordon <pgpatrickgordon@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
webbrowser = "0.3"
xdg = "2.1"

[dependencies.rss]
version = "1.6"
features = ["from_url"]
