#!/usr/bin/env python3
import os
import feedparser
import concurrent.futures
import webbrowser
import appdirs
import pathlib

config_dir = pathlib.Path(appdirs.user_config_dir('feed-browser'))
db_filename = config_dir / 'read.txt'
with open(db_filename) as db_file:
    read_links = set([x.strip() for x in db_file.readlines()])
with open(config_dir / 'feeds.txt') as feeds_file:
    rss_urls = set([x.strip() for x in feeds_file.readlines()])

with concurrent.futures.ThreadPoolExecutor(max_workers = 256) as executor:
    feeds = executor.map(feedparser.parse, rss_urls)

entries = [item for feed in feeds for item in feed['items']]
unread_links = [x.link for x in entries if x.link not in read_links]

[webbrowser.open(link) for link in unread_links]

read_links.update(unread_links)
with open(db_filename, 'w') as db_file:
    db_file.write('\n'.join(read_links))
